### ISSUE TITLE
Default implicit instance for `Console[IO]`

### ISSUE THREAD

**Issue by EnverOsmanov** [gvolpe/console4cats#1]
Maybe make `Console.io` object implicit?
```
implicit object io extends SyncConsole[IO]
```

**Comment by gvolpe** [comment]
Not sure what's the benefit other than saving two characters `._`?

Haven't seen many people using `implicit object`s for similar use cases, for example `http4s` also uses a similar approach to import a particular instance: `import org.http4s.client.dsl.io._` See [source](https://github.com/http4s/http4s/blob/master/client/src/main/scala/org/http4s/client/dsl/io.scala)

**Comment by EnverOsmanov** [comment]
I think it's needed for final tagless.
Let's take the example from [the guide](https://gvolpe.github.io/console4cats/guide.html). It doesn't work like that:
```
import cats.effect.IO
import cats.effect.Console

myProgram[IO]
```
and works like that:
```
import cats.effect.IO
import cats.effect.Console

implicit val ConsoleIO = Console.io
myProgram[IO]
```

**Comment by gvolpe** [comment]
I don't think that's related to final tagless @EnverOsmanov 

You can get an implicit instance of `Console[IO]` by just importing `import cats.effect.Console.io._` as shown in the guide.

**Comment by EnverOsmanov** [comment]
Have you tried running (or compile) `myProgram[IO]` with `import cats.effect.Console.io._`? It doesn't work for me.

**Comment by gvolpe** [comment]
I don't really know what `myProgram[IO]` is, can you share the code?

**Comment by EnverOsmanov** [comment]
It is from the [guide](https://gvolpe.github.io/console4cats/guide.html).
Ok, I'll share the code too:
```
object App {

  import Guide.myProgram
  import cats.effect.IO
  import cats.effect.Console.io._

  def main(args: Array[String]): Unit = {
    myProgram[IO].unsafeRunSync()
  }

}

object Guide {
  import cats.Monad
  import cats.effect.Console
  import cats.syntax.flatMap._
  import cats.syntax.functor._

  def myProgram[F[_]: Monad](implicit C: Console[F]): F[Unit] =
    for {
      _ <- C.putStrLn("Please enter your name: ")
      n <- C.readLn
      _ <- if (n.nonEmpty) C.putStrLn(s"Hello $n!")
      else C.putError("Name is empty!")
    } yield ()
}
```

**Comment by gvolpe** [comment]
That's right. In the guide the program that uses `IO` doesn't abstract over the effect.

In order to get your program working you need an implicit instance of `Console[IO]`, for example:

```scala
object App {

  import Guide.myProgram
  import cats.effect.IO

  implicit val consoleIO: Console[IO] = new SyncConsole[IO] // or Console.io'

  def main(args: Array[String]): Unit = {
    myProgram[IO].unsafeRunSync()
  }

}
```

**Comment by EnverOsmanov** [comment]
Ok. I just thought if there is a default implicit `Monad[IO]`, would be nice to have default implicit `Console[IO]`. Thanks for the library :) .

**Comment by gvolpe** [comment]
Not really. you can look [here](https://github.com/gvolpe/console4cats/blob/master/core/src/main/scala/cats/effect/Console.scala#L109) there is a default instance for any `F[_]: Sync]` but it is not available implicitly to avoid conflicts.

You can also look more at the history and arguments against providing a default implicit instance [here](https://github.com/typelevel/cats-effect/pull/256) since it was an original PR of `cats-effect`: 

Thanks :smiley:
